//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUP()
        {
            this.HR_JOB_POSITION = new HashSet<HR_JOB_POSITION>();
            this.GROUPS_USERS = new HashSet<GROUPS_USERS>();
            this.NOTIFICATIONS = new HashSet<NOTIFICATION>();
            this.PERMISSION_USERS_GROUP = new HashSet<PERMISSION_USERS_GROUP>();
        }
    
        public int ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ID_DEPARTMENT { get; set; }
        public string PURPOSE { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public int USER_CREATE { get; set; }
        public Nullable<int> MANAGER_ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_JOB_POSITION> HR_JOB_POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_USERS> GROUPS_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISSION_USERS_GROUP> PERMISSION_USERS_GROUP { get; set; }
    }
}
