//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUPS_USERS()
        {
            this.PERMISSION_DETAIL = new HashSet<PERMISSION_DETAIL>();
        }
    
        public int ID { get; set; }
        public int ID_GROUP { get; set; }
        public int ID_USER { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public int USER_CREATE { get; set; }
        public bool IS_LEADER { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISSION_DETAIL> PERMISSION_DETAIL { get; set; }
        public virtual USER USER { get; set; }
    }
}
