//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS_USERS_DELETED
    {
        public int ID { get; set; }
        public int ID_GROUP { get; set; }
        public int ID_USER { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public bool IS_LEADER { get; set; }
        public Nullable<System.DateTime> DATE_DELETE { get; set; }
        public Nullable<int> USER_DELETE { get; set; }
    }
}
