//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_DAILY_TASK_PROGRESS
    {
        public int ID { get; set; }
        public int ASSIGNEE { get; set; }
        public int TOTAL_TASK { get; set; }
        public int ONTIME_TASK { get; set; }
        public int DONE_LATE_TASK { get; set; }
        public int OVERDUE_TASK { get; set; }
        public int ONPROGRESS_TASK { get; set; }
        public int INREVIEW_TASK { get; set; }
        public System.DateTime DATE { get; set; }
    }
}
