//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EMPLOYEE
    {
        public int ID { get; set; }
        public int ID_USER { get; set; }
        public Nullable<int> ID_DEPARTMENT { get; set; }
        public string AVATAR { get; set; }
        public string ZALO { get; set; }
        public string NUMBER_PHONE { get; set; }
        public string PERSONAL_EMAIL { get; set; }
        public Nullable<System.DateTime> BIRTH_DAY { get; set; }
        public Nullable<System.DateTime> DATE_IN { get; set; }
        public Nullable<System.DateTime> DATE_OUT { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_OFFICIAL_EMPLOYEE { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
