//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_JOB_POSITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_JOB_POSITION()
        {
            this.TEMP_USER_POSITION = new HashSet<TEMP_USER_POSITION>();
            this.TEMP_WORKFLOW_POSITION = new HashSet<TEMP_WORKFLOW_POSITION>();
        }
    
        public int JD_ID { get; set; }
        public string JD_NAME { get; set; }
        public Nullable<int> JD_DEPARTMENT { get; set; }
        public Nullable<int> JD_GROUP_ID { get; set; }
        public Nullable<int> JD_INTERVIEWER { get; set; }
        public string JD_DESCRIPTION { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public string JD_REQUIREMENT { get; set; }
        public string JD_BENEFIT { get; set; }
        public string JD_CAPACITY { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual GROUP GROUP { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMP_USER_POSITION> TEMP_USER_POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMP_WORKFLOW_POSITION> TEMP_WORKFLOW_POSITION { get; set; }
    }
}
