//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK_REPORT_DAILY
    {
        public int ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> DATE_MEET_CLIENT { get; set; }
        public string TYPE_COMPANY { get; set; }
        public string CONTACT { get; set; }
        public string GENERAL_INFO { get; set; }
        public string PRODUCT { get; set; }
        public string COMPETITOR { get; set; }
        public string APPRECIATE { get; set; }
        public string PURPOSE { get; set; }
        public string ACTION { get; set; }
        public string RESULT { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
