//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int ID { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public string LINK { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string COMMENT { get; set; }
        public bool IS_READ { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual USER USER { get; set; }
    }
}
