//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION_DETAIL
    {
        public int ID { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> ID_GROUP_USER { get; set; }
        public int ID_TARGET { get; set; }
        public string TABLE_NAME { get; set; }
    
        public virtual GROUPS_USERS GROUPS_USERS { get; set; }
        public virtual USER USER { get; set; }
    }
}
