//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION_LIST
    {
        public int ID { get; set; }
        public string PERMISSION_NAME { get; set; }
        public string VIEW_APPLY { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public string TAGS { get; set; }
        public string SUB_PERMISSION { get; set; }
        public int ID_PERMISSION_TYPE { get; set; }
    
        public virtual PERMISSION_TYPE PERMISSION_TYPE { get; set; }
    }
}
