//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION_USERS_GROUP
    {
        public int ID { get; set; }
        public Nullable<int> ID_GROUP { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public string DESCRIPTION { get; set; }
        public int ID_PERMISSION { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual USER USER { get; set; }
    }
}
