//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_SCHEDULER_HISTORY
    {
        public int ID { get; set; }
        public int ID_PROJECT { get; set; }
        public System.DateTime DATE_CLONE { get; set; }
        public System.DateTime NEXT_DATE_CLONE { get; set; }
    }
}
