//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT()
        {
            this.TARGETS = new HashSet<TARGET>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public string PROJECT_NAME { get; set; }
        public int PROJECT_OWNER { get; set; }
        public string PROJECT_DESCRIPTION { get; set; }
        public string PROJECT_TARGERT { get; set; }
        public string PROJECT_STATUS { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<System.DateTime> DEADLINE_REQUIRE { get; set; }
        public string DEPT { get; set; }
        public string BRANCH { get; set; }
        public Nullable<bool> IS_MEETING { get; set; }
        public Nullable<System.TimeSpan> TIME_START { get; set; }
        public Nullable<System.TimeSpan> TIME_END { get; set; }
        public string PLACE { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARGET> TARGETS { get; set; }
    }
}
