//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_HEADER_MASTER
    {
        public int ID { get; set; }
        public string REPORT_NAME { get; set; }
        public Nullable<int> ID_DEPT { get; set; }
        public Nullable<int> BRANCH_ID { get; set; }
        public Nullable<int> ID_GROUP { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> VERSION { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public string HEADER_1 { get; set; }
        public string HEADER_2 { get; set; }
        public string HEADER_3 { get; set; }
        public string HEADER_4 { get; set; }
        public string HEADER_5 { get; set; }
        public string HEADER_6 { get; set; }
        public string HEADER_7 { get; set; }
        public string HEADER_8 { get; set; }
        public string HEADER_9 { get; set; }
        public string HEADER_10 { get; set; }
        public string HEADER_11 { get; set; }
        public string HEADER_12 { get; set; }
        public string HEADER_13 { get; set; }
        public string HEADER_14 { get; set; }
        public string HEADER_15 { get; set; }
        public string HEADER_16 { get; set; }
        public string HEADER_17 { get; set; }
        public string HEADER_18 { get; set; }
        public string HEADER_19 { get; set; }
        public string HEADER_20 { get; set; }
        public string HEADER_21 { get; set; }
        public string HEADER_22 { get; set; }
        public string HEADER_23 { get; set; }
        public string HEADER_24 { get; set; }
        public string HEADER_25 { get; set; }
        public string HEADER_26 { get; set; }
        public string HEADER_27 { get; set; }
        public string HEADER_28 { get; set; }
        public string HEADER_29 { get; set; }
        public string HEADER_30 { get; set; }
        public string HEADER_31 { get; set; }
        public string HEADER_32 { get; set; }
        public string HEADER_33 { get; set; }
        public string HEADER_34 { get; set; }
        public string HEADER_35 { get; set; }
        public string HEADER_36 { get; set; }
        public string HEADER_37 { get; set; }
        public string HEADER_38 { get; set; }
        public string HEADER_39 { get; set; }
        public string HEADER_40 { get; set; }
        public string HEADER_41 { get; set; }
        public string HEADER_42 { get; set; }
        public string HEADER_43 { get; set; }
        public string HEADER_44 { get; set; }
        public string HEADER_45 { get; set; }
        public string HEADER_46 { get; set; }
        public string HEADER_47 { get; set; }
        public string HEADER_48 { get; set; }
        public string HEADER_49 { get; set; }
        public string HEADER_50 { get; set; }
    }
}
