//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_COMMENT
    {
        public int ID { get; set; }
        public Nullable<int> ID_HEADER { get; set; }
        public Nullable<int> USER_COMMENT { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
