//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_SALE_PERFORMENT
    {
        public int ID { get; set; }
        public int ID_HEADER { get; set; }
        public Nullable<int> ID_DEPT { get; set; }
        public int WEEK { get; set; }
        public Nullable<int> MONTH { get; set; }
        public int YEAR { get; set; }
        public Nullable<bool> IS_PLAN { get; set; }
        public Nullable<int> ID_GROUP { get; set; }
        public Nullable<int> BRANCH_ID { get; set; }
        public Nullable<int> VERSION { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> SO_CUOI_GOI { get; set; }
        public Nullable<int> SO_BG { get; set; }
        public Nullable<decimal> DOANH_SO_BG { get; set; }
        public Nullable<decimal> DOANH_SO_SO { get; set; }
        public Nullable<decimal> DOANH_SO_THUC_HIEN { get; set; }
        public Nullable<decimal> TY_LE_TRUNG_DON { get; set; }
        public Nullable<int> SO_KH_PHAT_SINH { get; set; }
        public Nullable<int> KH_3THANG_CHUA_PS_BG { get; set; }
        public Nullable<int> KH_3THANG_CHUA_PS_SO { get; set; }
        public Nullable<int> KH_6THANG_CHUA_PS_BG { get; set; }
        public Nullable<int> KH_6THANG_CHUA_PS_SO { get; set; }
        public Nullable<int> KH_1NAM_CHUA_PS_BG { get; set; }
        public Nullable<int> KH_1NAM_CHUA_PS_SO { get; set; }
        public Nullable<decimal> TY_LE_CMT_BAO_GIA { get; set; }
    }
}
