//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_CONTENT_2020
    {
        public int ID { get; set; }
        public Nullable<int> ID_HEADER { get; set; }
        public Nullable<int> ID_DEPT { get; set; }
        public Nullable<int> ID_GROUP { get; set; }
        public int ID_USER { get; set; }
        public int VERSION { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
        public Nullable<System.DateTime> DATE_ACTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> WEEK { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<bool> IS_PLAN { get; set; }
        public string CONTENT_1 { get; set; }
        public string CONTENT_2 { get; set; }
        public string CONTENT_3 { get; set; }
        public string CONTENT_4 { get; set; }
        public string CONTENT_5 { get; set; }
        public string CONTENT_6 { get; set; }
        public string CONTENT_7 { get; set; }
        public string CONTENT_8 { get; set; }
        public string CONTENT_9 { get; set; }
        public string CONTENT_10 { get; set; }
        public string CONTENT_11 { get; set; }
        public string CONTENT_12 { get; set; }
        public string CONTENT_13 { get; set; }
        public string CONTENT_14 { get; set; }
        public string CONTENT_15 { get; set; }
        public string CONTENT_16 { get; set; }
        public string CONTENT_17 { get; set; }
        public string CONTENT_18 { get; set; }
        public string CONTENT_19 { get; set; }
        public string CONTENT_20 { get; set; }
        public string CONTENT_21 { get; set; }
        public string CONTENT_22 { get; set; }
        public string CONTENT_23 { get; set; }
        public string CONTENT_24 { get; set; }
        public string CONTENT_25 { get; set; }
        public string CONTENT_26 { get; set; }
        public string CONTENT_27 { get; set; }
        public string CONTENT_28 { get; set; }
        public string CONTENT_29 { get; set; }
        public string CONTENT_30 { get; set; }
        public string CONTENT_31 { get; set; }
        public string CONTENT_32 { get; set; }
        public string CONTENT_33 { get; set; }
        public string CONTENT_34 { get; set; }
        public string CONTENT_35 { get; set; }
        public string CONTENT_36 { get; set; }
        public string CONTENT_37 { get; set; }
        public string CONTENT_38 { get; set; }
        public string CONTENT_39 { get; set; }
        public string CONTENT_40 { get; set; }
        public string CONTENT_41 { get; set; }
        public string CONTENT_42 { get; set; }
        public string CONTENT_43 { get; set; }
        public string CONTENT_44 { get; set; }
        public string CONTENT_45 { get; set; }
        public string CONTENT_46 { get; set; }
        public string CONTENT_47 { get; set; }
        public string CONTENT_48 { get; set; }
        public string CONTENT_49 { get; set; }
        public string CONTENT_50 { get; set; }
    }
}
