//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SMART_OKRSEntities : DbContext
    {
        public SMART_OKRSEntities()
            : base("name=SMART_OKRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANCH> BRANCHes { get; set; }
        public virtual DbSet<COMMENT> COMMENTS { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<GROUPS_USERS> GROUPS_USERS { get; set; }
        public virtual DbSet<HISTORY_DAILY_TASK_PROGRESS> HISTORY_DAILY_TASK_PROGRESS { get; set; }
        public virtual DbSet<HR_EMPLOYEE> HR_EMPLOYEE { get; set; }
        public virtual DbSet<HR_JOB_POSITION> HR_JOB_POSITION { get; set; }
        public virtual DbSet<LOG_GROUPS_ACTIONS> LOG_GROUPS_ACTIONS { get; set; }
        public virtual DbSet<LOG_USER_ACTIONS> LOG_USER_ACTIONS { get; set; }
        public virtual DbSet<LOG_VIEWS> LOG_VIEWS { get; set; }
        public virtual DbSet<MARK_REPORT_DAILY> MARK_REPORT_DAILY { get; set; }
        public virtual DbSet<MEETING_ROOMS> MEETING_ROOMS { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONS { get; set; }
        public virtual DbSet<PERMISSION_DETAIL> PERMISSION_DETAIL { get; set; }
        public virtual DbSet<PERMISSION_LIST> PERMISSION_LIST { get; set; }
        public virtual DbSet<PERMISSION_TYPE> PERMISSION_TYPE { get; set; }
        public virtual DbSet<PERMISSION_USERS_GROUP> PERMISSION_USERS_GROUP { get; set; }
        public virtual DbSet<PROJECT> PROJECTs { get; set; }
        public virtual DbSet<PROJECT_SCHEDULER> PROJECT_SCHEDULER { get; set; }
        public virtual DbSet<PROJECT_SCHEDULER_HISTORY> PROJECT_SCHEDULER_HISTORY { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SYSTEM_VIEWS> SYSTEM_VIEWS { get; set; }
        public virtual DbSet<TARGET> TARGETS { get; set; }
        public virtual DbSet<TASK_CHECK_LIST> TASK_CHECK_LIST { get; set; }
        public virtual DbSet<TASK> TASKS { get; set; }
        public virtual DbSet<TEMP_USER_POSITION> TEMP_USER_POSITION { get; set; }
        public virtual DbSet<TEMP_WORKFLOW_POSITION> TEMP_WORKFLOW_POSITION { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<WORK_LOGS> WORK_LOGS { get; set; }
        public virtual DbSet<WORKFLOW> WORKFLOWs { get; set; }
        public virtual DbSet<WORKFLOW_DETAIL> WORKFLOW_DETAIL { get; set; }
        public virtual DbSet<WORKFLOW_TRANSITION> WORKFLOW_TRANSITION { get; set; }
        public virtual DbSet<GROUPS_USERS_DELETED> GROUPS_USERS_DELETED { get; set; }
        public virtual DbSet<LOG_GROUPS_USERS_ACTIONS> LOG_GROUPS_USERS_ACTIONS { get; set; }
    
        public virtual ObjectResult<List_Meeting_Rooms_Result> List_Meeting_Rooms(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Meeting_Rooms_Result>("List_Meeting_Rooms", currentuseridParameter);
        }
    
        public virtual int Proc_call_Proc_CLONE_PROJECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_call_Proc_CLONE_PROJECT");
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_CheckPermissionCRUD_Permission_List(string iduser)
        {
            var iduserParameter = iduser != null ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_CheckPermissionCRUD_Permission_List", iduserParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_CheckPermissionCRUD_Processing_Default(string iduser)
        {
            var iduserParameter = iduser != null ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_CheckPermissionCRUD_Processing_Default", iduserParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_CheckPermissionCRUD_TARGET(string iduser)
        {
            var iduserParameter = iduser != null ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_CheckPermissionCRUD_TARGET", iduserParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_CheckPermissionCRUD_TASKS(string iduser)
        {
            var iduserParameter = iduser != null ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_CheckPermissionCRUD_TASKS", iduserParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_CheckPermissionCRUD_USER(string iduser)
        {
            var iduserParameter = iduser != null ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_CheckPermissionCRUD_USER", iduserParameter);
        }
    
        public virtual int Proc_CLONE_PROJECT(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_CLONE_PROJECT", dateParameter);
        }
    
        public virtual ObjectResult<Proc_Daily_Progress_Result> Proc_Daily_Progress(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> deptid, string tungay, string denngay)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            var tungayParameter = tungay != null ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(string));
    
            var denngayParameter = denngay != null ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Daily_Progress_Result>("Proc_Daily_Progress", currentuseridParameter, groupidParameter, deptidParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Proc_Details_Target_Result> Proc_Details_Target(Nullable<int> targetid)
        {
            var targetidParameter = targetid.HasValue ?
                new ObjectParameter("targetid", targetid) :
                new ObjectParameter("targetid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Details_Target_Result>("Proc_Details_Target", targetidParameter);
        }
    
        public virtual ObjectResult<Proc_Details_Target_Taskid_Result> Proc_Details_Target_Taskid(Nullable<int> taskid)
        {
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Details_Target_Taskid_Result>("Proc_Details_Target_Taskid", taskidParameter);
        }
    
        public virtual ObjectResult<Proc_Details_Task_Result> Proc_Details_Task(Nullable<int> taskid)
        {
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Details_Task_Result>("Proc_Details_Task", taskidParameter);
        }
    
        public virtual ObjectResult<Proc_Filter_Target_ByProject_Result> Proc_Filter_Target_ByProject(Nullable<int> projectid, Nullable<int> currentuserid)
        {
            var projectidParameter = projectid.HasValue ?
                new ObjectParameter("projectid", projectid) :
                new ObjectParameter("projectid", typeof(int));
    
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Filter_Target_ByProject_Result>("Proc_Filter_Target_ByProject", projectidParameter, currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_Filter_Task_ByProject_Result> Proc_Filter_Task_ByProject(Nullable<int> projectid, Nullable<int> currentuserid)
        {
            var projectidParameter = projectid.HasValue ?
                new ObjectParameter("projectid", projectid) :
                new ObjectParameter("projectid", typeof(int));
    
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Filter_Task_ByProject_Result>("Proc_Filter_Task_ByProject", projectidParameter, currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_Filter_Task_ByTarget_Result> Proc_Filter_Task_ByTarget(Nullable<int> targetid, Nullable<int> currentuserid)
        {
            var targetidParameter = targetid.HasValue ?
                new ObjectParameter("targetid", targetid) :
                new ObjectParameter("targetid", typeof(int));
    
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Filter_Task_ByTarget_Result>("Proc_Filter_Task_ByTarget", targetidParameter, currentuseridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_Filter_Task_ByTarget_Count(Nullable<int> targetid, Nullable<int> currentuserid)
        {
            var targetidParameter = targetid.HasValue ?
                new ObjectParameter("targetid", targetid) :
                new ObjectParameter("targetid", typeof(int));
    
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_Filter_Task_ByTarget_Count", targetidParameter, currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_FilterWork_List_Projects_Result> Proc_FilterWork_List_Projects(Nullable<int> currentuserid, string keyword, Nullable<bool> status)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_FilterWork_List_Projects_Result>("Proc_FilterWork_List_Projects", currentuseridParameter, keywordParameter, statusParameter);
        }
    
        public virtual ObjectResult<Proc_FilterWork_List_Target_Result> Proc_FilterWork_List_Target(Nullable<int> currentuserid, string keyword, Nullable<bool> status)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_FilterWork_List_Target_Result>("Proc_FilterWork_List_Target", currentuseridParameter, keywordParameter, statusParameter);
        }
    
        public virtual ObjectResult<Proc_FilterWork_List_Tasks_Result> Proc_FilterWork_List_Tasks(Nullable<int> currentuserid, string keyword, Nullable<bool> status)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_FilterWork_List_Tasks_Result>("Proc_FilterWork_List_Tasks", currentuseridParameter, keywordParameter, statusParameter);
        }
    
        public virtual ObjectResult<Proc_Get_User_Hierarchy_Result> Proc_Get_User_Hierarchy(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_User_Hierarchy_Result>("Proc_Get_User_Hierarchy", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_Get_User_Subordinate_Result> Proc_Get_User_Subordinate(Nullable<int> currentuserid, string keyword)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_User_Subordinate_Result>("Proc_Get_User_Subordinate", currentuseridParameter, keywordParameter);
        }
    
        public virtual ObjectResult<Proc_GetAll_List_tasks_Result> Proc_GetAll_List_tasks(Nullable<int> currentuserid, Nullable<int> projectid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var projectidParameter = projectid.HasValue ?
                new ObjectParameter("projectid", projectid) :
                new ObjectParameter("projectid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetAll_List_tasks_Result>("Proc_GetAll_List_tasks", currentuseridParameter, projectidParameter);
        }
    
        public virtual int Proc_InsertTASKS_To_HISTORY_DAILY_TASK_PROGRESS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_InsertTASKS_To_HISTORY_DAILY_TASK_PROGRESS");
        }
    
        public virtual ObjectResult<Proc_List_Departments_Result> Proc_List_Departments(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Departments_Result>("Proc_List_Departments", currentuseridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Departments_Count(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Departments_Count", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_List_Departments01_Result> Proc_List_Departments01(Nullable<int> currentuserid, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Departments01_Result>("Proc_List_Departments01", currentuseridParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Proc_List_Group_UserGroup_Result> Proc_List_Group_UserGroup(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> userid, Nullable<int> managerid, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var manageridParameter = managerid.HasValue ?
                new ObjectParameter("managerid", managerid) :
                new ObjectParameter("managerid", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Group_UserGroup_Result>("Proc_List_Group_UserGroup", currentuseridParameter, groupidParameter, useridParameter, manageridParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Group_UserGroup_Count(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> userid, Nullable<int> managerid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var manageridParameter = managerid.HasValue ?
                new ObjectParameter("managerid", managerid) :
                new ObjectParameter("managerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Group_UserGroup_Count", currentuseridParameter, groupidParameter, useridParameter, manageridParameter);
        }
    
        public virtual ObjectResult<Proc_List_Group_WorkLogs_Result> Proc_List_Group_WorkLogs(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, Nullable<int> sotrang)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var sotrangParameter = sotrang.HasValue ?
                new ObjectParameter("sotrang", sotrang) :
                new ObjectParameter("sotrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Group_WorkLogs_Result>("Proc_List_Group_WorkLogs", currentuseridParameter, groupidParameter, tungayParameter, denngayParameter, sotrangParameter);
        }
    
        public virtual ObjectResult<Proc_List_Groups_Result> Proc_List_Groups(Nullable<int> currentuserid, string groupname, string description, string purpose, Nullable<int> deptid, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupnameParameter = groupname != null ?
                new ObjectParameter("groupname", groupname) :
                new ObjectParameter("groupname", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var purposeParameter = purpose != null ?
                new ObjectParameter("purpose", purpose) :
                new ObjectParameter("purpose", typeof(string));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Groups_Result>("Proc_List_Groups", currentuseridParameter, groupnameParameter, descriptionParameter, purposeParameter, deptidParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Groups_Count(Nullable<int> currentuserid, string groupname, string descrioption, string purpose, Nullable<int> deptid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupnameParameter = groupname != null ?
                new ObjectParameter("groupname", groupname) :
                new ObjectParameter("groupname", typeof(string));
    
            var descrioptionParameter = descrioption != null ?
                new ObjectParameter("descrioption", descrioption) :
                new ObjectParameter("descrioption", typeof(string));
    
            var purposeParameter = purpose != null ?
                new ObjectParameter("purpose", purpose) :
                new ObjectParameter("purpose", typeof(string));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Groups_Count", currentuseridParameter, groupnameParameter, descrioptionParameter, purposeParameter, deptidParameter);
        }
    
        public virtual ObjectResult<Proc_List_GroupUsers_Result> Proc_List_GroupUsers(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> userid, Nullable<bool> isleader, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var isleaderParameter = isleader.HasValue ?
                new ObjectParameter("isleader", isleader) :
                new ObjectParameter("isleader", typeof(bool));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_GroupUsers_Result>("Proc_List_GroupUsers", currentuseridParameter, groupidParameter, useridParameter, isleaderParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_GroupUsers_Count(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> userid, Nullable<bool> isleader)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var isleaderParameter = isleader.HasValue ?
                new ObjectParameter("isleader", isleader) :
                new ObjectParameter("isleader", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_GroupUsers_Count", currentuseridParameter, groupidParameter, useridParameter, isleaderParameter);
        }
    
        public virtual ObjectResult<Proc_List_HR_Employee_Result> Proc_List_HR_Employee(Nullable<int> currentuserid, Nullable<int> userid, Nullable<int> deptid, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_HR_Employee_Result>("Proc_List_HR_Employee", currentuseridParameter, useridParameter, deptidParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_HR_Employee_Count(Nullable<int> currentuserid, Nullable<int> userid, Nullable<int> deptid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_HR_Employee_Count", currentuseridParameter, useridParameter, deptidParameter);
        }
    
        public virtual ObjectResult<Proc_List_Mark_Daily_Report_Result> Proc_List_Mark_Daily_Report(Nullable<int> currentuserid, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Mark_Daily_Report_Result>("Proc_List_Mark_Daily_Report", currentuseridParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Mark_Daily_Report_Count(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Mark_Daily_Report_Count", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_List_Meeting_Result> Proc_List_Meeting(Nullable<int> currentuserid, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Meeting_Result>("Proc_List_Meeting", currentuseridParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Proc_List_Notification_Result> Proc_List_Notification(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> userid_create, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var userid_createParameter = userid_create.HasValue ?
                new ObjectParameter("userid_create", userid_create) :
                new ObjectParameter("userid_create", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Notification_Result>("Proc_List_Notification", currentuseridParameter, groupidParameter, userid_createParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Notification_Count(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> userid_create, Nullable<int> isread)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var userid_createParameter = userid_create.HasValue ?
                new ObjectParameter("userid_create", userid_create) :
                new ObjectParameter("userid_create", typeof(int));
    
            var isreadParameter = isread.HasValue ?
                new ObjectParameter("isread", isread) :
                new ObjectParameter("isread", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Notification_Count", currentuseridParameter, groupidParameter, userid_createParameter, isreadParameter);
        }
    
        public virtual ObjectResult<Proc_List_Notification_NotRead_Result> Proc_List_Notification_NotRead(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Notification_NotRead_Result>("Proc_List_Notification_NotRead", currentuseridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Notification_NotRead_Count(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Notification_NotRead_Count", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_List_Notification01_Result> Proc_List_Notification01(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> userid_create, Nullable<int> isread, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var userid_createParameter = userid_create.HasValue ?
                new ObjectParameter("userid_create", userid_create) :
                new ObjectParameter("userid_create", typeof(int));
    
            var isreadParameter = isread.HasValue ?
                new ObjectParameter("isread", isread) :
                new ObjectParameter("isread", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Notification01_Result>("Proc_List_Notification01", currentuseridParameter, groupidParameter, userid_createParameter, isreadParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Proc_List_Permission_Result> Proc_List_Permission(Nullable<int> currentuserid, string permission_name, string view, Nullable<int> usercreate, Nullable<System.DateTime> date, string tag, string subpermission, Nullable<int> permission_type)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var permission_nameParameter = permission_name != null ?
                new ObjectParameter("permission_name", permission_name) :
                new ObjectParameter("permission_name", typeof(string));
    
            var viewParameter = view != null ?
                new ObjectParameter("view", view) :
                new ObjectParameter("view", typeof(string));
    
            var usercreateParameter = usercreate.HasValue ?
                new ObjectParameter("usercreate", usercreate) :
                new ObjectParameter("usercreate", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            var subpermissionParameter = subpermission != null ?
                new ObjectParameter("subpermission", subpermission) :
                new ObjectParameter("subpermission", typeof(string));
    
            var permission_typeParameter = permission_type.HasValue ?
                new ObjectParameter("permission_type", permission_type) :
                new ObjectParameter("permission_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Permission_Result>("Proc_List_Permission", currentuseridParameter, permission_nameParameter, viewParameter, usercreateParameter, dateParameter, tagParameter, subpermissionParameter, permission_typeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Permission_Count(Nullable<int> currentuserid, string permission_name, string view, Nullable<int> usercreate, Nullable<System.DateTime> date, string tag, string subpermission, Nullable<int> permission_type)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var permission_nameParameter = permission_name != null ?
                new ObjectParameter("permission_name", permission_name) :
                new ObjectParameter("permission_name", typeof(string));
    
            var viewParameter = view != null ?
                new ObjectParameter("view", view) :
                new ObjectParameter("view", typeof(string));
    
            var usercreateParameter = usercreate.HasValue ?
                new ObjectParameter("usercreate", usercreate) :
                new ObjectParameter("usercreate", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            var subpermissionParameter = subpermission != null ?
                new ObjectParameter("subpermission", subpermission) :
                new ObjectParameter("subpermission", typeof(string));
    
            var permission_typeParameter = permission_type.HasValue ?
                new ObjectParameter("permission_type", permission_type) :
                new ObjectParameter("permission_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Permission_Count", currentuseridParameter, permission_nameParameter, viewParameter, usercreateParameter, dateParameter, tagParameter, subpermissionParameter, permission_typeParameter);
        }
    
        public virtual ObjectResult<Proc_List_Permission_Users_Group_old_Result> Proc_List_Permission_Users_Group_old(string permission_name, Nullable<int> usercreate, Nullable<System.DateTime> date, string tag, string subpermission, Nullable<int> permission_type, Nullable<int> group, Nullable<int> user)
        {
            var permission_nameParameter = permission_name != null ?
                new ObjectParameter("permission_name", permission_name) :
                new ObjectParameter("permission_name", typeof(string));
    
            var usercreateParameter = usercreate.HasValue ?
                new ObjectParameter("usercreate", usercreate) :
                new ObjectParameter("usercreate", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            var subpermissionParameter = subpermission != null ?
                new ObjectParameter("subpermission", subpermission) :
                new ObjectParameter("subpermission", typeof(string));
    
            var permission_typeParameter = permission_type.HasValue ?
                new ObjectParameter("permission_type", permission_type) :
                new ObjectParameter("permission_type", typeof(int));
    
            var groupParameter = group.HasValue ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(int));
    
            var userParameter = user.HasValue ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Permission_Users_Group_old_Result>("Proc_List_Permission_Users_Group_old", permission_nameParameter, usercreateParameter, dateParameter, tagParameter, subpermissionParameter, permission_typeParameter, groupParameter, userParameter);
        }
    
        public virtual ObjectResult<Proc_List_Permission_UsersGroup_Result> Proc_List_Permission_UsersGroup(Nullable<int> currentuserid, Nullable<int> permissionid, Nullable<int> groupid, Nullable<int> userid, Nullable<int> permissiontpyeid, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var permissionidParameter = permissionid.HasValue ?
                new ObjectParameter("permissionid", permissionid) :
                new ObjectParameter("permissionid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var permissiontpyeidParameter = permissiontpyeid.HasValue ?
                new ObjectParameter("permissiontpyeid", permissiontpyeid) :
                new ObjectParameter("permissiontpyeid", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Permission_UsersGroup_Result>("Proc_List_Permission_UsersGroup", currentuseridParameter, permissionidParameter, groupidParameter, useridParameter, permissiontpyeidParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Permission_UsersGroup_Count(Nullable<int> currentuserid, Nullable<int> permissionid, Nullable<int> groupid, Nullable<int> userid, Nullable<int> permissiontpyeid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var permissionidParameter = permissionid.HasValue ?
                new ObjectParameter("permissionid", permissionid) :
                new ObjectParameter("permissionid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var permissiontpyeidParameter = permissiontpyeid.HasValue ?
                new ObjectParameter("permissiontpyeid", permissiontpyeid) :
                new ObjectParameter("permissiontpyeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Permission_UsersGroup_Count", currentuseridParameter, permissionidParameter, groupidParameter, useridParameter, permissiontpyeidParameter);
        }
    
        public virtual ObjectResult<Proc_List_Permission01_Result> Proc_List_Permission01(Nullable<int> currentuserid, string permission_name, string view, Nullable<int> usercreate, Nullable<System.DateTime> date, string tag, string subpermission, Nullable<int> permission_type, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var permission_nameParameter = permission_name != null ?
                new ObjectParameter("permission_name", permission_name) :
                new ObjectParameter("permission_name", typeof(string));
    
            var viewParameter = view != null ?
                new ObjectParameter("view", view) :
                new ObjectParameter("view", typeof(string));
    
            var usercreateParameter = usercreate.HasValue ?
                new ObjectParameter("usercreate", usercreate) :
                new ObjectParameter("usercreate", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            var subpermissionParameter = subpermission != null ?
                new ObjectParameter("subpermission", subpermission) :
                new ObjectParameter("subpermission", typeof(string));
    
            var permission_typeParameter = permission_type.HasValue ?
                new ObjectParameter("permission_type", permission_type) :
                new ObjectParameter("permission_type", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Permission01_Result>("Proc_List_Permission01", currentuseridParameter, permission_nameParameter, viewParameter, usercreateParameter, dateParameter, tagParameter, subpermissionParameter, permission_typeParameter, pagenumParameter);
        }
    
        public virtual int Proc_List_ProcessingDefault(Nullable<int> id_name_default)
        {
            var id_name_defaultParameter = id_name_default.HasValue ?
                new ObjectParameter("id_name_default", id_name_default) :
                new ObjectParameter("id_name_default", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_List_ProcessingDefault", id_name_defaultParameter);
        }
    
        public virtual int Proc_List_ProcessingDefault_Count(Nullable<int> currentuserid, Nullable<int> id_name_default)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var id_name_defaultParameter = id_name_default.HasValue ?
                new ObjectParameter("id_name_default", id_name_default) :
                new ObjectParameter("id_name_default", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_List_ProcessingDefault_Count", currentuseridParameter, id_name_defaultParameter);
        }
    
        public virtual int Proc_List_ProcessingDefault01(Nullable<int> currentuserid, Nullable<int> id_name_default, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var id_name_defaultParameter = id_name_default.HasValue ?
                new ObjectParameter("id_name_default", id_name_default) :
                new ObjectParameter("id_name_default", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_List_ProcessingDefault01", currentuseridParameter, id_name_defaultParameter, pagenumParameter);
        }
    
        public virtual int Proc_List_ProcessingDefaultName(string name_default)
        {
            var name_defaultParameter = name_default != null ?
                new ObjectParameter("name_default", name_default) :
                new ObjectParameter("name_default", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_List_ProcessingDefaultName", name_defaultParameter);
        }
    
        public virtual ObjectResult<Proc_List_Project_Scheduler_Result> Proc_List_Project_Scheduler(Nullable<int> currentuserid, string projectname, string frequently, Nullable<int> status, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var projectnameParameter = projectname != null ?
                new ObjectParameter("projectname", projectname) :
                new ObjectParameter("projectname", typeof(string));
    
            var frequentlyParameter = frequently != null ?
                new ObjectParameter("frequently", frequently) :
                new ObjectParameter("frequently", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Project_Scheduler_Result>("Proc_List_Project_Scheduler", currentuseridParameter, projectnameParameter, frequentlyParameter, statusParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Project_Scheduler_Count(Nullable<int> currentuserid, string projectname, string frequently, Nullable<bool> status)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var projectnameParameter = projectname != null ?
                new ObjectParameter("projectname", projectname) :
                new ObjectParameter("projectname", typeof(string));
    
            var frequentlyParameter = frequently != null ?
                new ObjectParameter("frequently", frequently) :
                new ObjectParameter("frequently", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Project_Scheduler_Count", currentuseridParameter, projectnameParameter, frequentlyParameter, statusParameter);
        }
    
        public virtual ObjectResult<Proc_List_Projects_Result> Proc_List_Projects(Nullable<int> currentuserid, string branch, string deptname, Nullable<int> userid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var deptnameParameter = deptname != null ?
                new ObjectParameter("deptname", deptname) :
                new ObjectParameter("deptname", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Projects_Result>("Proc_List_Projects", currentuseridParameter, branchParameter, deptnameParameter, useridParameter);
        }
    
        public virtual ObjectResult<Proc_List_Projects_Data_Result> Proc_List_Projects_Data(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Projects_Data_Result>("Proc_List_Projects_Data", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_List_Projects_UserViewer_Result> Proc_List_Projects_UserViewer(Nullable<int> projectid)
        {
            var projectidParameter = projectid.HasValue ?
                new ObjectParameter("projectid", projectid) :
                new ObjectParameter("projectid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Projects_UserViewer_Result>("Proc_List_Projects_UserViewer", projectidParameter);
        }
    
        public virtual int Proc_List_Status(Nullable<int> currentuserid, string statusname, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var statusnameParameter = statusname != null ?
                new ObjectParameter("statusname", statusname) :
                new ObjectParameter("statusname", typeof(string));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_List_Status", currentuseridParameter, statusnameParameter, pagenumParameter);
        }
    
        public virtual int Proc_List_Status_Count(Nullable<int> iduser, string statusname)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            var statusnameParameter = statusname != null ?
                new ObjectParameter("statusname", statusname) :
                new ObjectParameter("statusname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_List_Status_Count", iduserParameter, statusnameParameter);
        }
    
        public virtual ObjectResult<Proc_List_Targets_Tasks_Result> Proc_List_Targets_Tasks(Nullable<int> currentuserid, Nullable<int> projectid, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var projectidParameter = projectid.HasValue ?
                new ObjectParameter("projectid", projectid) :
                new ObjectParameter("projectid", typeof(int));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Targets_Tasks_Result>("Proc_List_Targets_Tasks", currentuseridParameter, projectidParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Proc_List_ToDoList_Result> Proc_List_ToDoList(Nullable<int> idtask)
        {
            var idtaskParameter = idtask.HasValue ?
                new ObjectParameter("idtask", idtask) :
                new ObjectParameter("idtask", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_ToDoList_Result>("Proc_List_ToDoList", idtaskParameter);
        }
    
        public virtual ObjectResult<Proc_List_Users_Result> Proc_List_Users(Nullable<int> currentuserid, string username, string fullname, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var fullnameParameter = fullname != null ?
                new ObjectParameter("fullname", fullname) :
                new ObjectParameter("fullname", typeof(string));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Users_Result>("Proc_List_Users", currentuseridParameter, usernameParameter, fullnameParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Users_Count(Nullable<int> currentuserid, string username, string fullname)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var fullnameParameter = fullname != null ?
                new ObjectParameter("fullname", fullname) :
                new ObjectParameter("fullname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Users_Count", currentuseridParameter, usernameParameter, fullnameParameter);
        }
    
        public virtual ObjectResult<Proc_List_Users_WithPermission_Result> Proc_List_Users_WithPermission(Nullable<int> currentuserid, string fullname)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var fullnameParameter = fullname != null ?
                new ObjectParameter("fullname", fullname) :
                new ObjectParameter("fullname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Users_WithPermission_Result>("Proc_List_Users_WithPermission", currentuseridParameter, fullnameParameter);
        }
    
        public virtual ObjectResult<Proc_listProject_user_Result> Proc_listProject_user(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listProject_user_Result>("Proc_listProject_user", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_ListTargets_Project_Result> Proc_ListTargets_Project(Nullable<int> id_project, Nullable<int> currentuserid)
        {
            var id_projectParameter = id_project.HasValue ?
                new ObjectParameter("Id_project", id_project) :
                new ObjectParameter("Id_project", typeof(int));
    
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ListTargets_Project_Result>("Proc_ListTargets_Project", id_projectParameter, currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Target_Recheck_Result> Proc_My_List_Target_Recheck(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Target_Recheck_Result>("Proc_My_List_Target_Recheck", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Target_Work_Result> Proc_My_List_Target_Work(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Target_Work_Result>("Proc_My_List_Target_Work", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Missed_Result> Proc_My_List_Tasks_Missed(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Missed_Result>("Proc_My_List_Tasks_Missed", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Missed_ByTargetID_Result> Proc_My_List_Tasks_Missed_ByTargetID(Nullable<int> currentuserid, Nullable<int> idtarget)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var idtargetParameter = idtarget.HasValue ?
                new ObjectParameter("idtarget", idtarget) :
                new ObjectParameter("idtarget", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Missed_ByTargetID_Result>("Proc_My_List_Tasks_Missed_ByTargetID", currentuseridParameter, idtargetParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Notyetstart_Result> Proc_My_List_Tasks_Notyetstart(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Notyetstart_Result>("Proc_My_List_Tasks_Notyetstart", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Onprogress_Result> Proc_My_List_Tasks_Onprogress(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Onprogress_Result>("Proc_My_List_Tasks_Onprogress", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Overdue_Result> Proc_My_List_Tasks_Overdue(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Overdue_Result>("Proc_My_List_Tasks_Overdue", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Recheck_Result> Proc_My_List_Tasks_Recheck(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Recheck_Result>("Proc_My_List_Tasks_Recheck", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Recheck_ByTargetID_Result> Proc_My_List_Tasks_Recheck_ByTargetID(Nullable<int> currentuserid, Nullable<int> idtarget)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var idtargetParameter = idtarget.HasValue ?
                new ObjectParameter("idtarget", idtarget) :
                new ObjectParameter("idtarget", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Recheck_ByTargetID_Result>("Proc_My_List_Tasks_Recheck_ByTargetID", currentuseridParameter, idtargetParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Work_Result> Proc_My_List_Tasks_Work(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Work_Result>("Proc_My_List_Tasks_Work", currentuseridParameter);
        }
    
        public virtual ObjectResult<Proc_My_List_Tasks_Work_By_TargetID_Result> Proc_My_List_Tasks_Work_By_TargetID(Nullable<int> currentuserid, Nullable<int> idtarget)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var idtargetParameter = idtarget.HasValue ?
                new ObjectParameter("idtarget", idtarget) :
                new ObjectParameter("idtarget", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_List_Tasks_Work_By_TargetID_Result>("Proc_My_List_Tasks_Work_By_TargetID", currentuseridParameter, idtargetParameter);
        }
    
        public virtual ObjectResult<Proc_My_WorkLog_Report_Result> Proc_My_WorkLog_Report(Nullable<int> currentuserid, Nullable<int> month, Nullable<int> year)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_My_WorkLog_Report_Result>("Proc_My_WorkLog_Report", currentuseridParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<Proc_Project_Result> Proc_Project()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Project_Result>("Proc_Project");
        }
    
        public virtual ObjectResult<Proc_Project_Gantt_target_Result> Proc_Project_Gantt_target(Nullable<int> projectid)
        {
            var projectidParameter = projectid.HasValue ?
                new ObjectParameter("projectid", projectid) :
                new ObjectParameter("projectid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Project_Gantt_target_Result>("Proc_Project_Gantt_target", projectidParameter);
        }
    
        public virtual ObjectResult<Proc_Project_Gantt_task_Result> Proc_Project_Gantt_task(Nullable<int> targetid)
        {
            var targetidParameter = targetid.HasValue ?
                new ObjectParameter("targetid", targetid) :
                new ObjectParameter("targetid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Project_Gantt_task_Result>("Proc_Project_Gantt_task", targetidParameter);
        }
    
        public virtual ObjectResult<Proc_Project_name_Result> Proc_Project_name(Nullable<int> id_project)
        {
            var id_projectParameter = id_project.HasValue ?
                new ObjectParameter("Id_project", id_project) :
                new ObjectParameter("Id_project", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Project_name_Result>("Proc_Project_name", id_projectParameter);
        }
    
        public virtual ObjectResult<Proc_Report_Daily_progress_Result> Proc_Report_Daily_progress(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> deptid, string tungay, string denngay)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            var tungayParameter = tungay != null ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(string));
    
            var denngayParameter = denngay != null ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Report_Daily_progress_Result>("Proc_Report_Daily_progress", currentuseridParameter, groupidParameter, deptidParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Proc_Report_Daily_Task_Result> Proc_Report_Daily_Task(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Report_Daily_Task_Result>("Proc_Report_Daily_Task", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Proc_Report_Daily_Task_Detail_Result> Proc_Report_Daily_Task_Detail(Nullable<int> currentuserid, string keyword, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Report_Daily_Task_Detail_Result>("Proc_Report_Daily_Task_Detail", currentuseridParameter, keywordParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Proc_report_task_assignment_by_member_Result> Proc_report_task_assignment_by_member(Nullable<int> currentuserid, Nullable<int> groupid, Nullable<int> deptid, string tungay, string denngay)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(int));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            var tungayParameter = tungay != null ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(string));
    
            var denngayParameter = denngay != null ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_report_task_assignment_by_member_Result>("Proc_report_task_assignment_by_member", currentuseridParameter, groupidParameter, deptidParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Proc_Target_Complete_ByDept_Result> Proc_Target_Complete_ByDept(Nullable<int> currentuserid, Nullable<int> month, Nullable<int> year)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Target_Complete_ByDept_Result>("Proc_Target_Complete_ByDept", currentuseridParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<Proc_Task_GetAllTask_Result> Proc_Task_GetAllTask(Nullable<int> currentuserid, string keyword)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Task_GetAllTask_Result>("Proc_Task_GetAllTask", currentuseridParameter, keywordParameter);
        }
    
        public virtual ObjectResult<Proc_Task_GetTodolist_By_Task_Result> Proc_Task_GetTodolist_By_Task(Nullable<int> taskid)
        {
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Task_GetTodolist_By_Task_Result>("Proc_Task_GetTodolist_By_Task", taskidParameter);
        }
    
        public virtual ObjectResult<Proc_Tasks_by_Target_Result> Proc_Tasks_by_Target(Nullable<int> id_Target, Nullable<int> currentuserid)
        {
            var id_TargetParameter = id_Target.HasValue ?
                new ObjectParameter("Id_Target", id_Target) :
                new ObjectParameter("Id_Target", typeof(int));
    
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Tasks_by_Target_Result>("Proc_Tasks_by_Target", id_TargetParameter, currentuseridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_UpdateAll_Notification(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_UpdateAll_Notification", useridParameter);
        }
    
        public virtual ObjectResult<Proc_Workflow_get_WF_by_DEPT_Result> Proc_Workflow_get_WF_by_DEPT(Nullable<int> deptid)
        {
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Workflow_get_WF_by_DEPT_Result>("Proc_Workflow_get_WF_by_DEPT", deptidParameter);
        }
    
        public virtual ObjectResult<Proc_Workflow_get_WFDetail_by_ID_Result> Proc_Workflow_get_WFDetail_by_ID(Nullable<int> workflowid)
        {
            var workflowidParameter = workflowid.HasValue ?
                new ObjectParameter("workflowid", workflowid) :
                new ObjectParameter("workflowid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Workflow_get_WFDetail_by_ID_Result>("Proc_Workflow_get_WFDetail_by_ID", workflowidParameter);
        }
    
        public virtual ObjectResult<Proc_Workflow_get_WFTransition_by_ID_Result> Proc_Workflow_get_WFTransition_by_ID(Nullable<int> workflowid)
        {
            var workflowidParameter = workflowid.HasValue ?
                new ObjectParameter("workflowid", workflowid) :
                new ObjectParameter("workflowid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Workflow_get_WFTransition_by_ID_Result>("Proc_Workflow_get_WFTransition_by_ID", workflowidParameter);
        }
    
        public virtual ObjectResult<Proc_Workflow_List_Data_Result> Proc_Workflow_List_Data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Workflow_List_Data_Result>("Proc_Workflow_List_Data");
        }
    
        public virtual ObjectResult<Nullable<int>> Prod_CheckPermissionCRUD_Project(Nullable<int> currentuserid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Prod_CheckPermissionCRUD_Project", currentuseridParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6d8c4273_1eb1_4b03_8fa8_eb96570dc1b4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6d8c4273_1eb1_4b03_8fa8_eb96570dc1b4");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_bbf1e713_65fe_4eb0_8a87_c64423e6be2b()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_bbf1e713_65fe_4eb0_8a87_c64423e6be2b");
        }
    }
}
