//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_VIEWS
    {
        public int ID { get; set; }
        public System.DateTime DATE_LOG { get; set; }
        public Nullable<int> USER_LOG { get; set; }
        public string VIEW_NAME { get; set; }
        public string CONTROLLER { get; set; }
        public string VIEW_POSITION { get; set; }
    }
}
