//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARGET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TARGET()
        {
            this.TASKS = new HashSet<TASK>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public int DEPARTMENT { get; set; }
        public string TARGET_NAME { get; set; }
        public int ID_PROJECT { get; set; }
        public int ASSIGNEE { get; set; }
        public Nullable<System.DateTime> DATE_COMPLETE { get; set; }
        public string TARGET_STATUS { get; set; }
        public string TARGET_DESCRIPTION { get; set; }
        public Nullable<int> RECHECK_USER { get; set; }
        public Nullable<System.DateTime> RECHECK_TIME { get; set; }
        public string RECHECK_COMMENT { get; set; }
        public bool IS_DONE { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<System.DateTime> DEADLINE_REQUIRE { get; set; }
        public string BRANCH { get; set; }
        public string DEPT_RELATED { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT1 { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASKS { get; set; }
    }
}
