//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASK()
        {
            this.TASK_CHECK_LIST = new HashSet<TASK_CHECK_LIST>();
            this.WORK_LOGS = new HashSet<WORK_LOGS>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public Nullable<int> DEPARTMENT { get; set; }
        public int ID_TARGET { get; set; }
        public string TASK_NAME { get; set; }
        public string TASK_DESCRIPTION { get; set; }
        public Nullable<int> ASSIGNEE { get; set; }
        public Nullable<System.DateTime> DATE_COMPLETE { get; set; }
        public string TASK_STATUS { get; set; }
        public Nullable<int> RECHECK_USER { get; set; }
        public Nullable<System.DateTime> RECHECK_TIME { get; set; }
        public string RECHECK_COMMENT { get; set; }
        public bool IS_DONE { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<System.DateTime> DEADLINE_REQUIRE { get; set; }
        public string BRANCH { get; set; }
        public string DEPT_RELATED { get; set; }
        public Nullable<int> WORKFLOW_ID { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT1 { get; set; }
        public virtual TARGET TARGET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_CHECK_LIST> TASK_CHECK_LIST { get; set; }
        public virtual WORKFLOW WORKFLOW { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual USER USER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_LOGS> WORK_LOGS { get; set; }
    }
}
