//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_CHECK_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASK_CHECK_LIST()
        {
            this.WORK_LOGS = new HashSet<WORK_LOGS>();
        }
    
        public int ID { get; set; }
        public int ID_TASK { get; set; }
        public string CONTENT_CHECKLIST { get; set; }
        public bool IS_DONE { get; set; }
        public Nullable<System.DateTime> DATE_DONE { get; set; }
        public Nullable<int> ASSIGNEE { get; set; }
        public Nullable<System.DateTime> DEADLINE { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public Nullable<int> ID_WORKFLOW_DETAIL { get; set; }
        public bool NEED_CHECK { get; set; }
        public bool IS_CHECK_OK { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual TASK TASK { get; set; }
        public virtual WORKFLOW_DETAIL WORKFLOW_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_LOGS> WORK_LOGS { get; set; }
    }
}
