//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_USER_POSITION
    {
        public int ID { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> JD_ID { get; set; }
    
        public virtual HR_JOB_POSITION HR_JOB_POSITION { get; set; }
        public virtual USER USER { get; set; }
    }
}
