//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.Units1 = new HashSet<Unit>();
        }
    
        public System.Guid Id { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public System.Guid ParentUnitId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public int ModerationStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units1 { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
