//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.GROUPS_USERS = new HashSet<GROUPS_USERS>();
            this.HR_EMPLOYEE = new HashSet<HR_EMPLOYEE>();
            this.HR_EMPLOYEE1 = new HashSet<HR_EMPLOYEE>();
            this.HR_JOB_POSITION = new HashSet<HR_JOB_POSITION>();
            this.NOTIFICATIONS = new HashSet<NOTIFICATION>();
            this.PERMISSION_DETAIL = new HashSet<PERMISSION_DETAIL>();
            this.PERMISSION_USERS_GROUP = new HashSet<PERMISSION_USERS_GROUP>();
            this.PROJECTs = new HashSet<PROJECT>();
            this.TARGETS = new HashSet<TARGET>();
            this.TARGETS1 = new HashSet<TARGET>();
            this.TASK_CHECK_LIST = new HashSet<TASK_CHECK_LIST>();
            this.TASKS = new HashSet<TASK>();
            this.TASKS1 = new HashSet<TASK>();
            this.TASKS2 = new HashSet<TASK>();
            this.TEMP_USER_POSITION = new HashSet<TEMP_USER_POSITION>();
            this.WORKFLOW_DETAIL = new HashSet<WORKFLOW_DETAIL>();
            this.WORK_LOGS = new HashSet<WORK_LOGS>();
        }
    
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string FULLNAME { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public int USER_CREATE { get; set; }
        public bool IS_ALLOWED { get; set; }
        public string AVATAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_USERS> GROUPS_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_EMPLOYEE> HR_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_EMPLOYEE> HR_EMPLOYEE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_JOB_POSITION> HR_JOB_POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISSION_DETAIL> PERMISSION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISSION_USERS_GROUP> PERMISSION_USERS_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARGET> TARGETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARGET> TARGETS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_CHECK_LIST> TASK_CHECK_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASKS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASKS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMP_USER_POSITION> TEMP_USER_POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKFLOW_DETAIL> WORKFLOW_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_LOGS> WORK_LOGS { get; set; }
    }
}
