//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WISE_REPORTEntities : DbContext
    {
        public WISE_REPORTEntities()
            : base("name=WISE_REPORTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<REPORT_CHECK> REPORT_CHECK { get; set; }
        public virtual DbSet<REPORT_COMMENT> REPORT_COMMENT { get; set; }
        public virtual DbSet<REPORT_CONTENT_2020> REPORT_CONTENT_2020 { get; set; }
        public virtual DbSet<REPORT_DAILY_RESULT_WARRANTY> REPORT_DAILY_RESULT_WARRANTY { get; set; }
        public virtual DbSet<REPORT_DAILY_RESULT_WARRANTY_REVERSE> REPORT_DAILY_RESULT_WARRANTY_REVERSE { get; set; }
        public virtual DbSet<REPORT_HEADER_MASTER> REPORT_HEADER_MASTER { get; set; }
        public virtual DbSet<REPORT_SALE_PERFORMENT> REPORT_SALE_PERFORMENT { get; set; }
    
        public virtual int DynamicPivotTableInSql(string columnToPivot, string listToPivot)
        {
            var columnToPivotParameter = columnToPivot != null ?
                new ObjectParameter("ColumnToPivot", columnToPivot) :
                new ObjectParameter("ColumnToPivot", typeof(string));
    
            var listToPivotParameter = listToPivot != null ?
                new ObjectParameter("ListToPivot", listToPivot) :
                new ObjectParameter("ListToPivot", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DynamicPivotTableInSql", columnToPivotParameter, listToPivotParameter);
        }
    
        public virtual int Proc_Get_Chart_Sale_Performent(string headerid, string datachart, string typetime)
        {
            var headeridParameter = headerid != null ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(string));
    
            var datachartParameter = datachart != null ?
                new ObjectParameter("datachart", datachart) :
                new ObjectParameter("datachart", typeof(string));
    
            var typetimeParameter = typetime != null ?
                new ObjectParameter("typetime", typetime) :
                new ObjectParameter("typetime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Get_Chart_Sale_Performent", headeridParameter, datachartParameter, typetimeParameter);
        }
    
        public virtual ObjectResult<Proc_Get_Report_Result> Proc_Get_Report(Nullable<int> currentuserid, Nullable<int> headerid, string content_1, string content_2, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var content_1Parameter = content_1 != null ?
                new ObjectParameter("content_1", content_1) :
                new ObjectParameter("content_1", typeof(string));
    
            var content_2Parameter = content_2 != null ?
                new ObjectParameter("content_2", content_2) :
                new ObjectParameter("content_2", typeof(string));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_Report_Result>("Proc_Get_Report", currentuseridParameter, headeridParameter, content_1Parameter, content_2Parameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_Get_Report_Count(Nullable<int> currentuserid, Nullable<int> headerid, string content_1, string content_2)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var content_1Parameter = content_1 != null ?
                new ObjectParameter("content_1", content_1) :
                new ObjectParameter("content_1", typeof(string));
    
            var content_2Parameter = content_2 != null ?
                new ObjectParameter("content_2", content_2) :
                new ObjectParameter("content_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_Get_Report_Count", currentuseridParameter, headeridParameter, content_1Parameter, content_2Parameter);
        }
    
        public virtual int Proc_Get_Report_dynamic(Nullable<int> currentuserid, Nullable<int> headerid, Nullable<int> deptid, string content_1, string content_2, string content_3, string content_4, string content_5, string content_6, string content_7, string content_8, string content_9, string content_10, string sort_content_1, string sort_content_2, string sort_content_3, string sort_content_4, string sort_content_5, string sort_content_6, string sort_content_7, string sort_content_8, string sort_content_9, string sort_content_10, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            var content_1Parameter = content_1 != null ?
                new ObjectParameter("content_1", content_1) :
                new ObjectParameter("content_1", typeof(string));
    
            var content_2Parameter = content_2 != null ?
                new ObjectParameter("content_2", content_2) :
                new ObjectParameter("content_2", typeof(string));
    
            var content_3Parameter = content_3 != null ?
                new ObjectParameter("content_3", content_3) :
                new ObjectParameter("content_3", typeof(string));
    
            var content_4Parameter = content_4 != null ?
                new ObjectParameter("content_4", content_4) :
                new ObjectParameter("content_4", typeof(string));
    
            var content_5Parameter = content_5 != null ?
                new ObjectParameter("content_5", content_5) :
                new ObjectParameter("content_5", typeof(string));
    
            var content_6Parameter = content_6 != null ?
                new ObjectParameter("content_6", content_6) :
                new ObjectParameter("content_6", typeof(string));
    
            var content_7Parameter = content_7 != null ?
                new ObjectParameter("content_7", content_7) :
                new ObjectParameter("content_7", typeof(string));
    
            var content_8Parameter = content_8 != null ?
                new ObjectParameter("content_8", content_8) :
                new ObjectParameter("content_8", typeof(string));
    
            var content_9Parameter = content_9 != null ?
                new ObjectParameter("content_9", content_9) :
                new ObjectParameter("content_9", typeof(string));
    
            var content_10Parameter = content_10 != null ?
                new ObjectParameter("content_10", content_10) :
                new ObjectParameter("content_10", typeof(string));
    
            var sort_content_1Parameter = sort_content_1 != null ?
                new ObjectParameter("sort_content_1", sort_content_1) :
                new ObjectParameter("sort_content_1", typeof(string));
    
            var sort_content_2Parameter = sort_content_2 != null ?
                new ObjectParameter("sort_content_2", sort_content_2) :
                new ObjectParameter("sort_content_2", typeof(string));
    
            var sort_content_3Parameter = sort_content_3 != null ?
                new ObjectParameter("sort_content_3", sort_content_3) :
                new ObjectParameter("sort_content_3", typeof(string));
    
            var sort_content_4Parameter = sort_content_4 != null ?
                new ObjectParameter("sort_content_4", sort_content_4) :
                new ObjectParameter("sort_content_4", typeof(string));
    
            var sort_content_5Parameter = sort_content_5 != null ?
                new ObjectParameter("sort_content_5", sort_content_5) :
                new ObjectParameter("sort_content_5", typeof(string));
    
            var sort_content_6Parameter = sort_content_6 != null ?
                new ObjectParameter("sort_content_6", sort_content_6) :
                new ObjectParameter("sort_content_6", typeof(string));
    
            var sort_content_7Parameter = sort_content_7 != null ?
                new ObjectParameter("sort_content_7", sort_content_7) :
                new ObjectParameter("sort_content_7", typeof(string));
    
            var sort_content_8Parameter = sort_content_8 != null ?
                new ObjectParameter("sort_content_8", sort_content_8) :
                new ObjectParameter("sort_content_8", typeof(string));
    
            var sort_content_9Parameter = sort_content_9 != null ?
                new ObjectParameter("sort_content_9", sort_content_9) :
                new ObjectParameter("sort_content_9", typeof(string));
    
            var sort_content_10Parameter = sort_content_10 != null ?
                new ObjectParameter("sort_content_10", sort_content_10) :
                new ObjectParameter("sort_content_10", typeof(string));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Get_Report_dynamic", currentuseridParameter, headeridParameter, deptidParameter, content_1Parameter, content_2Parameter, content_3Parameter, content_4Parameter, content_5Parameter, content_6Parameter, content_7Parameter, content_8Parameter, content_9Parameter, content_10Parameter, sort_content_1Parameter, sort_content_2Parameter, sort_content_3Parameter, sort_content_4Parameter, sort_content_5Parameter, sort_content_6Parameter, sort_content_7Parameter, sort_content_8Parameter, sort_content_9Parameter, sort_content_10Parameter, pagenumParameter);
        }
    
        public virtual int Proc_Get_Report_dynamic_Sale(Nullable<int> currentuserid, Nullable<int> headerid, Nullable<int> week, Nullable<int> month, Nullable<int> year, Nullable<int> quater, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var weekParameter = week.HasValue ?
                new ObjectParameter("week", week) :
                new ObjectParameter("week", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var quaterParameter = quater.HasValue ?
                new ObjectParameter("quater", quater) :
                new ObjectParameter("quater", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Get_Report_dynamic_Sale", currentuseridParameter, headeridParameter, weekParameter, monthParameter, yearParameter, quaterParameter, pagenumParameter);
        }
    
        public virtual int Proc_Get_Report_dynamic_Sale_old(Nullable<int> currentuserid, Nullable<int> headerid, string content_1, string content_2, string content_3, string content_4, string content_5, string content_6, string content_7, string content_8, string content_9, string content_10, string sort_content_1, string sort_content_2, string sort_content_3, string sort_content_4, string sort_content_5, string sort_content_6, string sort_content_7, string sort_content_8, string sort_content_9, string sort_content_10, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var content_1Parameter = content_1 != null ?
                new ObjectParameter("content_1", content_1) :
                new ObjectParameter("content_1", typeof(string));
    
            var content_2Parameter = content_2 != null ?
                new ObjectParameter("content_2", content_2) :
                new ObjectParameter("content_2", typeof(string));
    
            var content_3Parameter = content_3 != null ?
                new ObjectParameter("content_3", content_3) :
                new ObjectParameter("content_3", typeof(string));
    
            var content_4Parameter = content_4 != null ?
                new ObjectParameter("content_4", content_4) :
                new ObjectParameter("content_4", typeof(string));
    
            var content_5Parameter = content_5 != null ?
                new ObjectParameter("content_5", content_5) :
                new ObjectParameter("content_5", typeof(string));
    
            var content_6Parameter = content_6 != null ?
                new ObjectParameter("content_6", content_6) :
                new ObjectParameter("content_6", typeof(string));
    
            var content_7Parameter = content_7 != null ?
                new ObjectParameter("content_7", content_7) :
                new ObjectParameter("content_7", typeof(string));
    
            var content_8Parameter = content_8 != null ?
                new ObjectParameter("content_8", content_8) :
                new ObjectParameter("content_8", typeof(string));
    
            var content_9Parameter = content_9 != null ?
                new ObjectParameter("content_9", content_9) :
                new ObjectParameter("content_9", typeof(string));
    
            var content_10Parameter = content_10 != null ?
                new ObjectParameter("content_10", content_10) :
                new ObjectParameter("content_10", typeof(string));
    
            var sort_content_1Parameter = sort_content_1 != null ?
                new ObjectParameter("sort_content_1", sort_content_1) :
                new ObjectParameter("sort_content_1", typeof(string));
    
            var sort_content_2Parameter = sort_content_2 != null ?
                new ObjectParameter("sort_content_2", sort_content_2) :
                new ObjectParameter("sort_content_2", typeof(string));
    
            var sort_content_3Parameter = sort_content_3 != null ?
                new ObjectParameter("sort_content_3", sort_content_3) :
                new ObjectParameter("sort_content_3", typeof(string));
    
            var sort_content_4Parameter = sort_content_4 != null ?
                new ObjectParameter("sort_content_4", sort_content_4) :
                new ObjectParameter("sort_content_4", typeof(string));
    
            var sort_content_5Parameter = sort_content_5 != null ?
                new ObjectParameter("sort_content_5", sort_content_5) :
                new ObjectParameter("sort_content_5", typeof(string));
    
            var sort_content_6Parameter = sort_content_6 != null ?
                new ObjectParameter("sort_content_6", sort_content_6) :
                new ObjectParameter("sort_content_6", typeof(string));
    
            var sort_content_7Parameter = sort_content_7 != null ?
                new ObjectParameter("sort_content_7", sort_content_7) :
                new ObjectParameter("sort_content_7", typeof(string));
    
            var sort_content_8Parameter = sort_content_8 != null ?
                new ObjectParameter("sort_content_8", sort_content_8) :
                new ObjectParameter("sort_content_8", typeof(string));
    
            var sort_content_9Parameter = sort_content_9 != null ?
                new ObjectParameter("sort_content_9", sort_content_9) :
                new ObjectParameter("sort_content_9", typeof(string));
    
            var sort_content_10Parameter = sort_content_10 != null ?
                new ObjectParameter("sort_content_10", sort_content_10) :
                new ObjectParameter("sort_content_10", typeof(string));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Get_Report_dynamic_Sale_old", currentuseridParameter, headeridParameter, content_1Parameter, content_2Parameter, content_3Parameter, content_4Parameter, content_5Parameter, content_6Parameter, content_7Parameter, content_8Parameter, content_9Parameter, content_10Parameter, sort_content_1Parameter, sort_content_2Parameter, sort_content_3Parameter, sort_content_4Parameter, sort_content_5Parameter, sort_content_6Parameter, sort_content_7Parameter, sort_content_8Parameter, sort_content_9Parameter, sort_content_10Parameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Proc_Get_Report_Header_Result> Proc_Get_Report_Header(Nullable<int> headerid)
        {
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_Report_Header_Result>("Proc_Get_Report_Header", headeridParameter);
        }
    
        public virtual int Proc_Get_Report_Sale_Count(Nullable<int> currentuserid, Nullable<int> headerid, string content_1, string content_2)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var content_1Parameter = content_1 != null ?
                new ObjectParameter("content_1", content_1) :
                new ObjectParameter("content_1", typeof(string));
    
            var content_2Parameter = content_2 != null ?
                new ObjectParameter("content_2", content_2) :
                new ObjectParameter("content_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Get_Report_Sale_Count", currentuseridParameter, headeridParameter, content_1Parameter, content_2Parameter);
        }
    
        public virtual ObjectResult<Proc_Get_Report_Sale_Performent_Result> Proc_Get_Report_Sale_Performent(Nullable<int> currentuserid, Nullable<int> headerid, Nullable<int> year)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_Report_Sale_Performent_Result>("Proc_Get_Report_Sale_Performent", currentuseridParameter, headeridParameter, yearParameter);
        }
    
        public virtual int Proc_Get_Report_Sale_Performent_dynamic(Nullable<int> currentuserid, Nullable<int> headerid, Nullable<int> week, Nullable<int> month, Nullable<int> year, Nullable<int> quater, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var weekParameter = week.HasValue ?
                new ObjectParameter("week", week) :
                new ObjectParameter("week", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var quaterParameter = quater.HasValue ?
                new ObjectParameter("quater", quater) :
                new ObjectParameter("quater", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Get_Report_Sale_Performent_dynamic", currentuseridParameter, headeridParameter, weekParameter, monthParameter, yearParameter, quaterParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Proc_Get_Report_Sale_Performent_Plan_Result> Proc_Get_Report_Sale_Performent_Plan(Nullable<int> currentuserid, Nullable<int> headerid, Nullable<int> year)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_Report_Sale_Performent_Plan_Result>("Proc_Get_Report_Sale_Performent_Plan", currentuseridParameter, headeridParameter, yearParameter);
        }
    
        public virtual ObjectResult<Proc_Get_Report_Warranty_Result> Proc_Get_Report_Warranty(Nullable<int> currentuserid, Nullable<int> branch, Nullable<int> month, Nullable<int> year, string tungay, string denngay, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var tungayParameter = tungay != null ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(string));
    
            var denngayParameter = denngay != null ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(string));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_Report_Warranty_Result>("Proc_Get_Report_Warranty", currentuseridParameter, branchParameter, monthParameter, yearParameter, tungayParameter, denngayParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Proc_Get_Report_Warranty_All_Result> Proc_Get_Report_Warranty_All(Nullable<int> currentuserid, string branch, Nullable<int> month, Nullable<int> year, string tungay, string denngay)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var branchParameter = branch != null ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(string));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var tungayParameter = tungay != null ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(string));
    
            var denngayParameter = denngay != null ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Get_Report_Warranty_All_Result>("Proc_Get_Report_Warranty_All", currentuseridParameter, branchParameter, monthParameter, yearParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_Get_Report_Warranty_Count(Nullable<int> currentuserid, Nullable<int> branch, Nullable<int> month, Nullable<int> year, string tungay, string denngay)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var tungayParameter = tungay != null ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(string));
    
            var denngayParameter = denngay != null ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_Get_Report_Warranty_Count", currentuseridParameter, branchParameter, monthParameter, yearParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Proc_List_Report_Result> Proc_List_Report(Nullable<int> currentuserid, string report_name, Nullable<bool> ischeck, Nullable<int> deptid, Nullable<int> branch, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var report_nameParameter = report_name != null ?
                new ObjectParameter("report_name", report_name) :
                new ObjectParameter("report_name", typeof(string));
    
            var ischeckParameter = ischeck.HasValue ?
                new ObjectParameter("ischeck", ischeck) :
                new ObjectParameter("ischeck", typeof(bool));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Report_Result>("Proc_List_Report", currentuseridParameter, report_nameParameter, ischeckParameter, deptidParameter, branchParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Proc_List_Report_Comment_Result> Proc_List_Report_Comment(Nullable<int> currentuserid, Nullable<int> headerid, Nullable<int> pagenum)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_Report_Comment_Result>("Proc_List_Report_Comment", currentuseridParameter, headeridParameter, pagenumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Report_Comment_Count(Nullable<int> currentuserid, Nullable<int> headerid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Report_Comment_Count", currentuseridParameter, headeridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_List_Report_Count(Nullable<int> currentuserid, string report_name, Nullable<bool> ischeck, Nullable<int> branch, Nullable<int> deptid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var report_nameParameter = report_name != null ?
                new ObjectParameter("report_name", report_name) :
                new ObjectParameter("report_name", typeof(string));
    
            var ischeckParameter = ischeck.HasValue ?
                new ObjectParameter("ischeck", ischeck) :
                new ObjectParameter("ischeck", typeof(bool));
    
            var branchParameter = branch.HasValue ?
                new ObjectParameter("branch", branch) :
                new ObjectParameter("branch", typeof(int));
    
            var deptidParameter = deptid.HasValue ?
                new ObjectParameter("deptid", deptid) :
                new ObjectParameter("deptid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_List_Report_Count", currentuseridParameter, report_nameParameter, ischeckParameter, branchParameter, deptidParameter);
        }
    
        public virtual ObjectResult<Proc_List_User_View_Report_Result> Proc_List_User_View_Report(Nullable<int> currentuserid, Nullable<int> headerid)
        {
            var currentuseridParameter = currentuserid.HasValue ?
                new ObjectParameter("currentuserid", currentuserid) :
                new ObjectParameter("currentuserid", typeof(int));
    
            var headeridParameter = headerid.HasValue ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_List_User_View_Report_Result>("Proc_List_User_View_Report", currentuseridParameter, headeridParameter);
        }
    
        public virtual int Proc_Sale_Performent_DynamicPivotTable(string columnToPivot, string listToPivot)
        {
            var columnToPivotParameter = columnToPivot != null ?
                new ObjectParameter("ColumnToPivot", columnToPivot) :
                new ObjectParameter("ColumnToPivot", typeof(string));
    
            var listToPivotParameter = listToPivot != null ?
                new ObjectParameter("ListToPivot", listToPivot) :
                new ObjectParameter("ListToPivot", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Sale_Performent_DynamicPivotTable", columnToPivotParameter, listToPivotParameter);
        }
    
        public virtual ObjectResult<Proc_Sale_Performent_DynamicPivotTable_Month_Result> Proc_Sale_Performent_DynamicPivotTable_Month(string headerid)
        {
            var headeridParameter = headerid != null ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Sale_Performent_DynamicPivotTable_Month_Result>("Proc_Sale_Performent_DynamicPivotTable_Month", headeridParameter);
        }
    
        public virtual int Proc_Sale_Performent_DynamicPivotTable_Week(string headerid)
        {
            var headeridParameter = headerid != null ?
                new ObjectParameter("headerid", headerid) :
                new ObjectParameter("headerid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Sale_Performent_DynamicPivotTable_Week", headeridParameter);
        }
    }
}
