//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKFLOW()
        {
            this.TASKS = new HashSet<TASK>();
            this.TEMP_WORKFLOW_POSITION = new HashSet<TEMP_WORKFLOW_POSITION>();
            this.WORKFLOW_TRANSITION = new HashSet<WORKFLOW_TRANSITION>();
            this.WORKFLOW_DETAIL = new HashSet<WORKFLOW_DETAIL>();
        }
    
        public int ID { get; set; }
        public string WORKFLOW_NAME { get; set; }
        public string JOB_TITLE { get; set; }
        public string DESCRIPTIONS { get; set; }
        public bool IS_USING { get; set; }
        public double WORKFLOW_VERSION { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMP_WORKFLOW_POSITION> TEMP_WORKFLOW_POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKFLOW_TRANSITION> WORKFLOW_TRANSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKFLOW_DETAIL> WORKFLOW_DETAIL { get; set; }
    }
}
