//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKFLOW_DETAIL()
        {
            this.TASK_CHECK_LIST = new HashSet<TASK_CHECK_LIST>();
        }
    
        public int ID { get; set; }
        public int WORKFLOW_ID { get; set; }
        public int STEP { get; set; }
        public string STEP_NAME { get; set; }
        public Nullable<int> ASSIGNEE { get; set; }
        public string DESCRIPTIONS { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public string figure { get; set; }
        public string fill { get; set; }
        public Nullable<int> keystep { get; set; }
        public string loc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_CHECK_LIST> TASK_CHECK_LIST { get; set; }
        public virtual USER USER { get; set; }
        public virtual WORKFLOW WORKFLOW { get; set; }
    }
}
