//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_LOGS
    {
        public int ID { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<int> USER_CREATE { get; set; }
        public int ID_TASK { get; set; }
        public string RESULT_WORK { get; set; }
        public System.DateTime TIME_LOG { get; set; }
        public Nullable<int> RECHECK_USER { get; set; }
        public Nullable<System.DateTime> RECHECK_TIME { get; set; }
        public string RECHECK_RECOMMENT { get; set; }
        public string TIME_SPENT { get; set; }
        public Nullable<decimal> HOUR_SPENT { get; set; }
        public string TITLE_WORKLOG { get; set; }
        public Nullable<System.DateTime> TIME_START { get; set; }
        public Nullable<System.DateTime> TIME_END { get; set; }
        public Nullable<int> ID_CHECK_LIST { get; set; }
        public bool IS_WORKING { get; set; }
    
        public virtual TASK_CHECK_LIST TASK_CHECK_LIST { get; set; }
        public virtual TASK TASK { get; set; }
        public virtual USER USER { get; set; }
    }
}
