//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wise_Report.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_TRANSITION
    {
        public int ID { get; set; }
        public int WORKFLOW_ID { get; set; }
        public bool NEED_CHECK { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public bool IS_CHECK_OK { get; set; }
        public Nullable<int> fromnode { get; set; }
        public Nullable<int> tonode { get; set; }
        public string fromPort { get; set; }
        public string toPort { get; set; }
        public string points { get; set; }
    
        public virtual WORKFLOW WORKFLOW { get; set; }
    }
}
